### ISSUE TITLE
fix caching

### ISSUE THREAD

**Issue by jeremymanning** [jeremymanning/hypertools#3]
Caching is really useful when the goal is to re-run the same line of code multiple times (it makes subsequent runs faster).  But the current implementation of caching seems to be ignoring some parameters.  For example, calling `plot` with the `reduce` flag returns a `DataGeometry` object (as expected).  However, subsequent calls to plot using the same dataset (but a different `reduce` argument) seem to return the same object, rather than calling `reduce` again with the new argument.

Ideas:
- The simplest way to fix this would be to entirely remove caching.
- Alternatively, we could add a `cache` flag to specify whether or not to cache a particular function call.  When `cache==False`, this could force a "refresh" of whatever function was being called, as a sort of hack to fix the undesired behavior
- The "best" solution would to actually figure out why caching isn't working as expected and then fix it.

Plan:
- Try the simplest solution first and then build from there...

**Comment by paxtonfitzpatrick** [comment]
hey @jeremymanning can you post some code to reproduce this?  I can't get it to happen on my end with either the main plot function or the `DataGeometry.plot` method.  There's definitely something fishy is going on if you're getting duplicate outputs... especially because the plot function is never actually cached.

**Comment by jeremymanning** [comment]
the issue seems to be related to our caching not properly handling keyword arguments.  we "stringify" data and *some* arguments, but keyword arguments passed to functions aren't properly converted into strings, nor are complex data structures like nested dictionaries.  therefore multiply calls to the same function with the same data (but different arguments) can result in the cached results being returned, effectively ignoring changed arguments.

**Comment by jeremymanning** [comment]
let's get rid of caching...too many problems to justify keeping this feature
